J-Dunny/fitlit

- src/user.js
- test/user-test.js
> Add User test

- src/UserRepository.js
- test/UserRepository-test.js
> User repo/rf

- dist/index.html
- src/css/styles.css
> Add step goal html/css

- dist/index.html
- src/css/styles.css
> Add html/css outline

- src/apiCalls.js
- src/scripts.js
> Add User Data Fetch Call and Dom manipulation

- src/HydrationRepository.js
- src/apiCalls.js
- src/scripts.js
- src/user.js
- test/HydrationRepository-test.js
> Continue hydration api fetch and test

- dist/index.html
- src/css/styles.css
- src/scripts.js
> Add displayHydrationInfo method to scripts.js

- dist/index.html
- src/css/styles.css
- src/scripts.js
> Add CSS for hydration week data

- dist/index.html
- src/css/styles.css
- src/scripts.js
> Add Css to dashboard

- src/HydrationRepository.js
- src/scripts.js
- test/HydrationRepository-test.js
> Refactor hydrationrepo for 1 week

- dist/index.html
- src/css/styles.css
- src/scripts.js
- src/user.js
> Add User info and friends

- src/SleepRepository.js
- src/data/sleep.js
- test/SleepRepository-test.js
> Add Sleep functionality

- src/SleepRepository.js
- test/SleepRepository-test.js
> Add sleep for week functionality

- src/HydrationRepository.js
- src/SleepRepository.js
- src/css/styles.css
- src/scripts.js
- test/HydrationRepository-test.js
- test/SleepRepository-test.js
> Add test files for date data

- dist/index.html
- src/css/styles.css
- src/scripts.js
> Fix username

- src/HydrationRepository.js
- src/SleepRepository.js
- src/UserRepository.js
- src/user.js
- test/HydrationRepository-test.js
- test/SleepRepository-test.js
- test/UserRepository-test.js
- test/user-test.js
> Refactor part one general

- src/Activity.js
- test/activity-test.js
> Add activity-test

- dist/index.html
- src/Activity.js
- src/SleepRepository.js
- src/apiCalls.js
- src/scripts.js
- test/activity-test.js
> Added methods to actvity and updated DOM

- dist/index.html
- src/apiCalls.js
- src/scripts.js
> Add hydration form functionality

- dist/index.html
- src/apiCalls.js
- src/scripts.js
> Add activity form functionality

- dist/index.html
- src/SleepRepository.js
- src/scripts.js
> Refactor sleep display

- dist/index.html
- src/SleepRepository.js
- src/scripts.js
> Fix sleep display and input

- dist/index.html
- src/css/styles.css
- src/scripts.js
> Fix string issue and CSS

- dist/index.html
- src/Activity.js
- src/HydrationRepository.js
- src/SleepRepository.js
- src/apiCalls.js
- src/css/styles.css
- src/scripts.js
> Refactor for submission
